use upgraded fzf kill function

diff --git a/shell/dot_sh_setup b/shell/dot_sh_setup
--- a/shell/dot_sh_setup
+++ b/shell/dot_sh_setup
@@ -33,3 +33,20 @@ virtualenv_prompt() {
     if [[ -z $v ]]; then return 0; fi
     echo "$BLUE [$v] $NO_COLOR"
 }
+
+# fkill - kill processes - list only the ones you can kill. Modified the earlier script.
+# https://github.com/junegunn/fzf/wiki/examples
+fkill() {
+    command -v fzf > /dev/null || { echo 'fzf not found'; exit; }
+    local pid
+    if [ "$UID" != "0" ]; then
+        pid=$(ps -f -u $UID | sed 1d | fzf -m | awk '{print $2}')
+    else
+        pid=$(ps -ef | sed 1d | fzf -m | awk '{print $2}')
+    fi
+
+    if [ "x$pid" != "x" ]
+    then
+        echo $pid | xargs kill -${1:-9}
+    fi
+}
